- name: Install base packages
  become: true
  ansible.builtin.apt:
    name: "{{ base_packages.all + base_packages.debian }}"
    state: present
    update_cache: true

- name: Install GUI Packages if enabled
  become: true
  community.general.apt:
    name: "{{ gui_packages.all + gui_packages.debian }}"
    state: present
  when: install_gui
