- name: Create main user
  register: user_creation
  become: true
  ansible.builtin.user:
    state: present
    name: besole
    shell: /bin/zsh
    password: '$6$nSq1/wer4fZZTWzK$ZXf.RdrKP1lWZiaYMbHXE.iaMOJOIA6/2bYM4Fq50twbpGOvf3J5kQtnHuAV9A9PZ6xUs4fhTkDgSpx2qbzXZ.'
    generate_ssh_key: true
    ssh_key_type: ecdsa
    ssh_key_comment: besole@{{ inventory_hostname }}

- name: Allow sudo access
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/besole
    content: |
      besole ALL=(ALL) NOPASSWD:ALL

- name: Copy ssh keys
  become: true
  ansible.posix.authorized_key:
    exclusive: true
    state: present
    user: besole
    key: |
      {% for keyfile in lookup('ansible.builtin.fileglob', 'ssh-pubkeys/*', wantlist=true) %}
      {{ lookup('ansible.builtin.file', keyfile) }}
      {% endfor %}

- name: Clone dotfiles
  become: true
  become_user: besole
  ansible.builtin.git:
    accept_newhostkey: true
    dest: "{{ user_creation.home }}/userbuild/git/dotfiles"
    force: true
    repo: https://github.com/besole/dotfiles.git
    version: "{{ dotfiles_version | default('master') }}"
    
- name: Initialize dotfiles
  become: true
  become_user: besole
  ansible.builtin.shell:
    cmd: "{{ user_creation.home }}/userbuild/git/dotfiles/init.sh"
