- name: Generate locales
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - zsh
      - git
    state: present
    update_cache: true

- name: Create main user
  register: user_creation
  become: true
  ansible.builtin.user:
    state: present
    name: besole
    shell: /bin/zsh
    password: '$6$XA/dV4wYoDCnW5jX$TVC3n7i8KB19KsYNrbtn1LBxUVGYvU.p6UEM0fCEpZUDYetq9/sGfXnPSLbnphy63X8QT65AmkNZFy2QAABu9/'
    generate_ssh_key: true
    ssh_key_type: ecdsa
    ssh_key_comment: besole@{{ inventory_hostname }}

- name: Set up dotfiles for besole
  become: true
  become_user: besole
  block:
    - name: Clone dotfiles
      ansible.builtin.git:
        accept_newhostkey: true
        dest: "{{ user_creation.home }}/userbuild/git/dotfiles"
        force: true
        repo: https://github.com/besole/dotfiles.git
    
    - name: Initialize dotfiles
      ansible.builtin.shell:
        cmd: "{{ user_creation.home }}/userbuild/git/dotfiles/init.sh"
