- name: Create main user
  register: user_creation
  become: true
  ansible.builtin.user:
    state: present
    name: besole
    shell: /bin/zsh
    password_lock: true
    generate_ssh_key: true
    ssh_key_type: ecdsa
    ssh_key_comment: besole@{{ inventory_hostname }}

- name: Allow sudo access
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/besole
    content: |
      besole ALL=(ALL) NOPASSWD:ALL

- name: Copy ssh keys
  become: true
  ansible.posix.authorized_key:
    exclusive: true
    state: present
    user: besole
    key: |
      {% for keyfile in lookup('ansible.builtin.fileglob', 'ssh-pubkeys/*', wantlist=true) %}
      {{ lookup('ansible.builtin.file', keyfile) }}
      {% endfor %}

- name: Clone dotfiles
  become: true
  become_user: besole
      ansible.builtin.git:
        accept_newhostkey: true
        dest: "{{ user_creation.home }}/userbuild/git/dotfiles"
        force: true
        repo: https://github.com/besole/dotfiles.git
    
- name: Initialize dotfiles
  become: true
  become_user: besole
  ansible.builtin.shell:
    cmd: "{{ user_creation.home }}/userbuild/git/dotfiles/init.sh"
