- name: Set up ansible requirements
  hosts: all
  tasks:
#    - name: Install ansible galaxy collections
#      community.general.ansible_galaxy_install:
#        dest: "{{ playbook_dir }}/../collections/"
#        requirements_file: "{{ playbook_dir }}/../collections/requirements.yml"
#        type: collection
#
#    - name: Install ansible galaxy roles
#      community.general.ansible_galaxy_install:
#        dest: "{{ playbook_dir }}/../roles/"
#        requirements_file: "{{ playbook_dir }}/../roles/requirements.yml"
#        type: role
    - name: Install ansible galaxy collections
      ansible.builtin.command:
        chdir: ..
        cmd: ansible-galaxy collection install -r collections/requirements.yml

    - name: Install ansible galaxy roles
      ansible.builtin.command: 
        chdir: ..
        cmd: ansible-galaxy role install -r roles/requirements.yml
