- name: Set up ansible requirements
  hosts: all
  tasks:
    - name: Install ansible galaxy collections
      community.general.ansible_galaxy_install:
        requirements_file: "{{ playbook_dir }}/../collections/requirements.yml"
        type: collection

    - name: Install ansible galaxy roles
      community.general.ansible_galaxy_install:
        requirements_file: "{{ playbook_dir }}/../roles/requirements.yml"
        type: role
