- name: Set up ansible requirements
  hosts: all
  tasks:
    - name: Install ansible galaxy collections
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install -r {{ playbook_dir }}/collections/requirements.yml -p {{ playbook_dir }}/collections --force

    - name: Install ansible galaxy roles
      ansible.builtin.shell:
        cmd: ansible-galaxy role install -r {{ playbook_dir }}/roles/requirements.yml -p {{ playbook_dir}}/roles --force
