- name: Set up ansible requirements
  hosts: all

  pre_tasks:
    - name: Stop running on localhost if specific hostname was found
      ansible.builtin.meta: end_host
      when:
        - inventory_hostname == "localhost"
        - ansible_play_hosts | length > 1

  tasks:
    - name: Install ansible galaxy collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r collections/requirements.yml

    - name: Install ansible galaxy roles
      ansible.builtin.command: 
        cmd: ansible-galaxy role install -r roles/requirements.yml
