- name: Configure Host OS
  hosts: localhost,all

  pre_tasks:
    - name: Stop running on localhost if specific hostname was found
      ansible.builtin.meta: end_host
      when:
        - inventory_hostname == "localhost"
        - ansible_play_hosts | length > 1

  roles:
    - besole.os.config
    - besole.user.zsh
